# Generated by Django 3.1.7 on 2021-04-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение')),
                ('processor', models.CharField(default='', max_length=50)),
                ('memory', models.CharField(default='', max_length=50)),
                ('videocard', models.CharField(default='', max_length=50)),
                ('motherboard', models.CharField(default='', max_length=50)),
                ('cores_count', models.CharField(default='', max_length=30)),
                ('core_frequency', models.CharField(default='', max_length=30)),
                ('hard_drive', models.CharField(default='', max_length=100)),
                ('soft_drive', models.CharField(default='', max_length=100)),
                ('price', models.FloatField(default=0.0, max_length=50)),
            ],
        ),
    ]
