# Generated by Django 3.1.7 on 2021-04-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20210427_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pc',
            name='image',
            field=models.ImageField(default='../static/images/keyboard.png', upload_to='images/', verbose_name='Изображение'),
        ),
    ]
